/** 
 * EMSL-API generated by eMoflon::Neo - Do not edit as this file will be overwritten
 */
package org.emoflon.neo.api;			
import org.emoflon.neo.neo4j.adapter.models.NeoCoreBuilder;

public class API_Common {
	// Default values (might have to be changed)
	public static final String PLATFORM_PLUGIN_URI = "/C:/Users/Suganya/Downloads/eclipse-dsl-new/eclipse/plugins/";
	public static final String PLATFORM_RESOURCE_URI = "../";

	public static NeoCoreBuilder createBuilder() {
		return new NeoCoreBuilder("bolt://localhost:7687", "neo4j", "Graph");
	}
}
